/* Generated By:JavaCC: Do not edit this line. AnalizadorLexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SUMA = 6;
  /** RegularExpression Id. */
  int MULTIPLICACION = 7;
  /** RegularExpression Id. */
  int ASIGNACION = 8;
  /** RegularExpression Id. */
  int RESTA = 9;
  /** RegularExpression Id. */
  int DIVISION = 10;
  /** RegularExpression Id. */
  int MAYORQUE = 11;
  /** RegularExpression Id. */
  int MENORQUE = 12;
  /** RegularExpression Id. */
  int TERMINALDELINEA = 13;
  /** RegularExpression Id. */
  int ENTERO = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int CONDICIONALSI = 16;
  /** RegularExpression Id. */
  int CONDICIONALFINSI = 17;
  /** RegularExpression Id. */
  int CONDICIONALDELOCONTRARIO = 18;
  /** RegularExpression Id. */
  int CONDICIONALENTONCES = 19;
  /** RegularExpression Id. */
  int ESCRIBIR = 20;
  /** RegularExpression Id. */
  int LEER = 21;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 22;
  /** RegularExpression Id. */
  int DIGIT = 23;
  /** RegularExpression Id. */
  int LMINUS = 24;
  /** RegularExpression Id. */
  int NUMEROENTERO = 25;
  /** RegularExpression Id. */
  int COMENTARIOS = 26;
  /** RegularExpression Id. */
  int CADENADETEXTO = 27;
  /** RegularExpression Id. */
  int CONCATENACION = 28;
  /** RegularExpression Id. */
  int CORCHETEABRE = 29;
  /** RegularExpression Id. */
  int CORCHETECIERRA = 30;
  /** RegularExpression Id. */
  int COMA = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"+\"",
    "\"*\"",
    "\"=\"",
    "\"-\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\".\"",
    "\"Numero\"",
    "\"Cadena\"",
    "\"Si\"",
    "\"FinSi\"",
    "\"Sino\"",
    "\"Entonces\"",
    "\"Escribir\"",
    "\"Leer\"",
    "<IDENTIFICADOR>",
    "<DIGIT>",
    "<LMINUS>",
    "<NUMEROENTERO>",
    "<COMENTARIOS>",
    "<CADENADETEXTO>",
    "<CONCATENACION>",
    "\"[\"",
    "\"]\"",
    "\",\"",
  };

}
