/* Generated By:JavaCC: Do not edit this line. AnalizadorLexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SUMA = 6;
  /** RegularExpression Id. */
  int MULTIPLICACION = 7;
  /** RegularExpression Id. */
  int ASIGNACION = 8;
  /** RegularExpression Id. */
  int RESTA = 9;
  /** RegularExpression Id. */
  int DIVISION = 10;
  /** RegularExpression Id. */
  int MAYORQUE = 11;
  /** RegularExpression Id. */
  int MENORQUE = 12;
  /** RegularExpression Id. */
  int ENTERO = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int CONDICIONALSI = 15;
  /** RegularExpression Id. */
  int CONDICIONALDELOCONTRARIO = 16;
  /** RegularExpression Id. */
  int ESCRIBIR = 17;
  /** RegularExpression Id. */
  int LEER = 18;
  /** RegularExpression Id. */
  int NUMEROENTERO = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 21;
  /** RegularExpression Id. */
  int CORCHETEABRE = 22;
  /** RegularExpression Id. */
  int CORCHETECIERRA = 23;
  /** RegularExpression Id. */
  int PUNTO = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"+\"",
    "\"*\"",
    "\"=\"",
    "\"-\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"Numero\"",
    "\"Cadena\"",
    "\"Si\"",
    "\"Sino\"",
    "\"Escribir\"",
    "\"Leer\"",
    "<NUMEROENTERO>",
    "<DIGIT>",
    "<IDENTIFICADOR>",
    "\"[\"",
    "\"]\"",
    "\".\"",
  };

}
