/* Generated By:JavaCC: Do not edit this line. compTreeConstants.java Version 5.0 */
public interface compTreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTSENTENCIAS = 1;
  public int JJTSIMPLESTM = 2;
  public int JJTCONDICIONAL = 3;
  public int JJTCONDICIONALSI = 4;
  public int JJTCONDICIONALENTONCES = 5;
  public int JJTCONDICIONALDELOCONTRARIO = 6;
  public int JJTCONDICIONALFINSI = 7;
  public int JJTDAT = 8;
  public int JJTIDENTIFICADOR = 9;
  public int JJTNUMEROENTERO = 10;
  public int JJTOPCION = 11;
  public int JJTMENORQUE = 12;
  public int JJTMAYORQUE = 13;
  public int JJTMAYORIGUAL = 14;
  public int JJTMENORIGUAL = 15;
  public int JJTCOMPARAR = 16;
  public int JJTDIFERENTE = 17;
  public int JJTASIGNACION = 18;
  public int JJTTERMINAL = 19;
  public int JJTVALOR = 20;
  public int JJTCADENATEXTO = 21;
  public int JJTCONCATENACION = 22;
  public int JJTCORCHETEABRE = 23;
  public int JJTCORCHETECIERRA = 24;
  public int JJTOPERADORES = 25;
  public int JJTOPERADORADD = 26;
  public int JJTOPERADORMULT = 27;
  public int JJTLEER = 28;
  public int JJTESCRIBIR = 29;
  public int JJTDATOS = 30;
  public int JJTCONCATENACIONES = 31;
  public int JJTDECLARACION = 32;
  public int JJTENTERO = 33;
  public int JJTSTRING = 34;
  public int JJTMASIDS = 35;
  public int JJTCOMA = 36;


  public String[] jjtNodeName = {
    "Programa",
    "Sentencias",
    "SimpleStm",
    "condicional",
    "CONDICIONALSI",
    "CONDICIONALENTONCES",
    "CONDICIONALDELOCONTRARIO",
    "CONDICIONALFINSI",
    "dat",
    "IDENTIFICADOR",
    "NUMEROENTERO",
    "opcion",
    "MENORQUE",
    "MAYORQUE",
    "MAYORIGUAL",
    "MENORIGUAL",
    "COMPARAR",
    "DIFERENTE",
    "asignacion",
    "TERMINAL",
    "valor",
    "CADENATEXTO",
    "CONCATENACION",
    "CORCHETEABRE",
    "CORCHETECIERRA",
    "operadores",
    "OPERADORADD",
    "OPERADORMULT",
    "leer",
    "escribir",
    "datos",
    "concatenaciones",
    "declaracion",
    "ENTERO",
    "STRING",
    "masIds",
    "COMA",
  };
}
/* JavaCC - OriginalChecksum=7e89817bb0cc0cda19ff2d158a1eddcd (do not edit this line) */
