/* Generated By:JJTree&JavaCC: Do not edit this line. compConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO = 5;
  /** RegularExpression Id. */
  int SI = 6;
  /** RegularExpression Id. */
  int ENTONCES = 7;
  /** RegularExpression Id. */
  int FINSI = 8;
  /** RegularExpression Id. */
  int DELOCONTRARIO = 9;
  /** RegularExpression Id. */
  int FINDELOCONTRARIO = 10;
  /** RegularExpression Id. */
  int ASIGNAR = 11;
  /** RegularExpression Id. */
  int COMPARAR = 12;
  /** RegularExpression Id. */
  int MAYORQ = 13;
  /** RegularExpression Id. */
  int MENORQ = 14;
  /** RegularExpression Id. */
  int MAYORIGUAL = 15;
  /** RegularExpression Id. */
  int MENORIGUAL = 16;
  /** RegularExpression Id. */
  int DIFERENTE = 17;
  /** RegularExpression Id. */
  int COMILLA = 18;
  /** RegularExpression Id. */
  int ABREC = 19;
  /** RegularExpression Id. */
  int CIERRAC = 20;
  /** RegularExpression Id. */
  int ADD_OP = 21;
  /** RegularExpression Id. */
  int MULT_OP = 22;
  /** RegularExpression Id. */
  int NUMERO = 23;
  /** RegularExpression Id. */
  int CADENA = 24;
  /** RegularExpression Id. */
  int LEER = 25;
  /** RegularExpression Id. */
  int ESCRIBIR = 26;
  /** RegularExpression Id. */
  int NUMBER = 27;
  /** RegularExpression Id. */
  int ID = 28;
  /** RegularExpression Id. */
  int CADENADETEXTO = 29;
  /** RegularExpression Id. */
  int CONCATENAR = 30;
  /** RegularExpression Id. */
  int TERMINALDELINEA = 31;
  /** RegularExpression Id. */
  int FINARCH = 32;
  /** RegularExpression Id. */
  int COMA = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "<COMENTARIO>",
    "\"Si\"",
    "\"Entonces\"",
    "\"FinSi\"",
    "\"Sino\"",
    "\"FinSino\"",
    "\"=\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"\\\"\"",
    "\"[\"",
    "\"]\"",
    "<ADD_OP>",
    "<MULT_OP>",
    "\"Numero\"",
    "\"Cadena\"",
    "\"Leer\"",
    "\"Escribir\"",
    "<NUMBER>",
    "<ID>",
    "<CADENADETEXTO>",
    "\"@\"",
    "\".\"",
    "\"?\"",
    "\",\"",
  };

}
